- subcommittee/coding-guidelines/README.md
- subcommittee/coding-guidelines/members.md
- subcommittee/coding-guidelines/mission-statement.md
Hey folks :wave: 
I'm opening a PR to put some initial thoughts behind the coding guidelines subcommittee based on our kick-off at RustConf.
What I'd like help with:
* If you're interested in becoming a member and not on the list, please sound off here in the PR. The process for becoming a member of the consortium and of subcommittees is still being formulated and I don't want to miss anyone.
* If your name is listed under `members.md` and you **no longer wish to be involved**, please let me know. I know life can get busy :grin: 
* If you're aware of other resources we can highlight in the section on the state of Rust coding guidelines for safety-critical that'd be super helpful to give a shout out here.
* Or you can message me privately on Zulip if you have a company-specific document …
> Add initial structure for coding guidelines subcommittee

- subcommittee/tooling/README.md
- subcommittee/tooling/members.md
- subcommittee/tooling/mission-statement.md
This pull request adds the documents to kickstart the tooling subcommittee. Please feel free to suggest any changes that you think are necessary.
Thanks @PLeVasseur for setting up a good template for the subcommittee.
Thank you.
> Kickstart tooling subcommittee

- subcommittee/coding-guidelines/contributor-expectations.md
- subcommittee/coding-guidelines/initiatives/safe-use-of-unsafe-guidelines/safe-use-of-unsafe-guidelines-proposal.md
- subcommittee/coding-guidelines/meetings/22-October-2024/minutes.md
* Meeting minutes
* ~Contributor Expectations~
* Striking these from the record in favor of a rewrite which will be workshopped [here](https://github.com/rustfoundation/safety-critical-rust-consortium/pull/57)
* Safe Use of Unsafe Guidelines
> [Coding Guidelines] Add meeting minutes and draft docs from 22-October-2024 meeting

- subcommittee/coding-guidelines/contributor-expectations.md
Following todays meeting, I quickly noted down what I heard from the group.
@plevasseur and I quickly made it a round draft.
This is very much a first stab at another work document. Please liberally leave feedback.
> Positive, encouraging contributor expectations

- subcommittee/coding-guidelines/meetings/19-November-2024/agenda.md
Hey folks :wave: 
Welcome any agenda items we'd like to bring here to go ahead and leave as comments.
> 19-November-2024 meeting agenda draft

- subcommittee/coding-guidelines/initiatives/safe-use-of-unsafe-guidelines/safe-use-of-unsafe-guidelines-proposal.md
- subcommittee/coding-guidelines/initiatives/safe-use-of-unsafe-guidelines/unsafe-example-usage.md
- subcommittee/coding-guidelines/meetings/19-November-2024/agenda.md
Add unsafe Rust coding considerations
> Update agenda with Learn unsafe Rust

- subcommittee/tooling/meetings/22-November-2024/agenda.md
This pull request adds the initial agenda proposal for the tooling subcommittee meeting on 22.11.
[Rendered](https://github.com/rustfoundation/safety-critical-rust-consortium/blob/410a76533031997e4241b736bac2dadccd8bb411/subcommittee/tooling/meetings/22-November-2024/agenda.md)
> Tooling subcommittee: Meeting 22.11 agenda

- subcommittee/tooling/members.md
I will replace Fabrice for this from now on.
> Tooling subcommittee: replace Fabrice Derepas with Sasha Pourcelot

- subcommittee/coding-guidelines/meetings/2024-December-04/minutes.md
Feel free to suggest changes if I didn't properly capture anyone's proposals or questions
> [Coding Guidelines] Add meeting minutes 2024-12-04

- subcommittee/coding-guidelines/members.md
Adding in new members :slightly_smiling_face: 
closes #118 
closes #116 
closes #111 
closes #99 
closes #102
> [Coding Guidelines] Add new Coding Guidelines Subcommittee members

- subcommittee/tooling/members.md
This pull request adds members to the Tooling Subcommittee.
It closes #115, closes #113, closes #112, closes #103, closes #105.
> [Tooling] add members

- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new coding guidelines subcommittee member

- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new coding guidelines subcommittee members.

- subcommittee/coding-guidelines/meetings/2025-January-15/minutes.md
Feel free to suggest changes if I didn't correctly capture any topics of discussion.
> [Coding Guidelines] Add meeting minutes 2025-01-15

- subcommittee/coding-guidelines/meetings/2025-January-29/minutes.md
Adding an agenda for 2025 January 29. Feel free to suggest any agenda topics to be added.
> [Coding Guidelines] Agenda 2025-01-29

- subcommittee/coding-guidelines/members.md
closes #166 
closes #161 
closes #164 
closes #170 
closes #156
> Add new members, reformat as table with more info

- subcommittee/coding-guidelines/members.md
> Add new member

- subcommittee/coding-guidelines/members.md
Leaving this open ahead of our next meeting on 2025-02-26 as a catch-all to keep adding folks. I will add you to the meetings as I add you here. Will close after our meeting on 2025-02-26 and go back to adding members as we go.
closes #197
closes #199
closes #201
closes #195
closes #204 
closes #205 
closes #207
> [Coding Guidelines] Add new members 2025-02-24

- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new members

- subcommittee/tooling/meetings/10-January-2025/minutes.md
The pull request adds the meeting minutes of the 10-January-2025.
Please use GitHub comments to add items to the *Needs to Standards* mapping.
> [Tooling] Meeting minutes 10-January-2025

- subcommittee/tooling/meetings/07-February-2025/minutes.md
This pull request adds the meeting notes for the 7th February meeting. The output table that we have decide upon is not available in a different pull request #175.
> [tooling] meeting notes 7 February 2025

- subcommittee/coding-guidelines/members.md
Hey @jonititan -- I saw on your consortium application you listed your full first name, on your subcommittee application you used your shortened version. I saw you usually use the shortened version, so I used it here. If you'd like me to change it to the full version let me know :)
closes #218
> [Coding Guidelines] Add new coding guidelines member

- subcommittee/coding-guidelines/members.md
closes #243 
closes #242 
closes #235
> [Coding Guidlines] Add new members

- subcommittee/coding-guidelines/meetings/2025-03-12/minutes.md
Most likely a bit non-uniform, like perhaps too thorough at times and too superficial at other times, but hopefully understandable and didn't miss any critical content.
> [Coding Guidelines] Minutes 12thMarch2025

- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new coding guidlines member

- subcommittee/liaison/meetings/2025-03-28/minutes.md
Hey @AlexCeleste -- I think I can't pick you as reviewer yet, so I'm pinging you here.
> [Liaison] Add meeting notes from 2025-03-28

- subcommittee/coding-guidelines/meetings/2025-04-09/minutes.md
Howdy folks 👋 Based on what we discussed today I'd like for us to spend the majority of next time on ensuring clarity of terms being used and fleshing out the how to read / how to write sections.
Feel free to comment on other items you'd like to bring.
> [Coding Guidelines] Add agenda for 2025-04-09

- subcommittee/coding-guidelines/meetings/2025-04-16/minutes.md
Hey everyone 👋 we'll continue with a working session to drive towards consensus on terminology.
> [Coding Guidelines] Add agenda for 2025-04-16

- subcommittee/coding-guidelines/initiatives/safe-use-of-unsafe-guidelines/learn_unsafe_rust/src/core_unsafety/abi_and_ffi.md
This is the first PR for https://github.com/rustfoundation/safety-critical-rust-consortium/issues/150, adding some initial stuff for the chapter.
> Initial content for "ABI and FFI" of "Learn unsafe Rust"

- subcommittee/coding-guidelines/meetings/2025-04-23/minutes.md
This PR includes the commits from https://github.com/rustfoundation/safety-critical-rust-consortium/pull/284.
> Add minutes from 2025-04-23 meeting

- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new members 2025-04-28

- subcommittee/tooling/meetings/2025-04-18/minutes.md
[Rendered](https://github.com/rustfoundation/safety-critical-rust-consortium/blob/46cb888ce44d5754b80c515a165064d2622a5d9e/subcommittee/tooling/meetings/2025-04-18/minutes.md)
> Added meeting minutes from April 18 2025 tooling subcommittee meeting

- .github/workflows/arewesafetycriticalyet-org-test.yml
- .github/workflows/arewesafetycriticalyet-org.yml
I think this will stop the redirect from arewesafetycriticalyet.org to arewesafetycriticalyet.org/website
> Publish website to root

- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Adding new members 2025-05-20

- meetings/2024-09-10/minutes.md
- meetings/2025-02-19/minutes.md
- meetings/2025-05-15/minutes.md
- projects/state of rust adoption survey/2025/Results/2025_SCRC_AdoptionSurvey_AllResponses.csv
- Adding (virtual) presence
- Cleaning unnecessary/embarrassing private data from Survey Results (not altering main inputs/points anyway)
> MoMs & Sensitive Data

- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new members - 2025-06-02

- subcommittee/coding-guidelines/meetings/2025-06-10/minutes.md
Hey folks 👋 here's the agenda for our first Asia-Pacific + Americas meeting.
I kept the agenda a bit simple this time as I want to gauge the Asia-Pacific turnout 🌏
> [Coding Guidelines] Add agenda for 2025-06-10

- subcommittee/coding-guidelines/meetings/2025-06-18/minutes.md
Adds the agenda for the Asia Pacific / Europe meeting.
I'll be chairing this meeting in Pete's stead since the times line up better for someone in Tokyo.
> [Coding Guidelines] Agenda for 2025-06-18

- subcommittee/coding-guidelines/meetings/2025-07-22/minutes.md
> meeting minutes 7/22

- arewesafetycriticalyet.org/docs/coding_guidelines/members.md
- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add coding guidelines member 2025-07-12

- arewesafetycriticalyet.org/docs/coding_guidelines/members.md
- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new members 2025-08-06

- arewesafetycriticalyet.org/docs/coding_guidelines/members.md
- subcommittee/coding-guidelines/members.md
> [Coding Guidelines] Add new members 2025-08-29

- subcommittee/coding-guidelines/meetings/2025-08-27/minutes.md
Hey folks 👋 here's our agenda for tomorrow.
Feel free to suggest additions here if you've got them.
> [Coding Guidelines] Add agenda for 2025-08-27

- subcommittee/coding-guidelines/meetings/2025-09-23/minutes.md
Hey folks 👋 feel free to leave ideas here on what you'd like to bring if any additional topics
> [Coding Guidelines] Agenda for 2025-09-23

- arewesafetycriticalyet.org/docs/tooling/members.md
- subcommittee/tooling/members.md
This pull request adds a new member to the tooling subcommittee.
closes #440
> [tooling] add new members
